name: Rime
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          directories=$(ls -d */)
          for directory in $directories; do
            dirname=$(basename $directory)
            if [[ $dirname == "_common" ]]; then
              continue
            fi
            echo ::group::$dirname
            rime test $dirname
            echo ::endgroup::
          done
